server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


router-properties:
  services:
    ACCOUNT-SERVICE:
      prefix: /ACCOUNT
      service-url: lb://ACCOUNT-SERVER
      routes:
        - path: /account/**
        - path: /accountMovement/**
        - path: /report/**

    CLIENT-SERVICE:
      prefix: /CLIENT
      service-url: lb://CLIENT-SERVER
      routes:
        - path: /client/**

